version: '3.8'
services:
  laravel.test:
    build:
      context: .
      dockerfile: ./vendor/laravel/sail/runtimes/8.5/Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        LARAVEL_SAIL: 1
    image: sail-8.5/app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql
      - mailpit

  mysql:
    image: 'mysql:8.0'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bd_videojuegos
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '${MAILPIT_PORT:-8025}:8025'
    networks:
      - sail

volumes:
  sail-mysql:

networks:
  sail:
    driver: bridge